# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('fur', models.CharField(max_length=50))
            ],
        ),
    ]
