# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'cats'),
        ),
    ]
