# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180215_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='litter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Litter'),
        ),
    ]
